contacts/urls.py
from os import name
from django.urls import path
from . import views
app_name = 'contacts'

urlpatterns=[
    path('',views.home,name='home'),
    path('manual/',views.manualEntry,name='manualEntry'),
    path('match/',views.matchFields,name='matchFields'),
]

funnels/urls.py
from os import name
from django.urls import path
from . import views
app_name = 'funnels'

urlpatterns=[
    path('',views.starterforfunnel,name='starterforfunnel'),
    path('createfun/',views.createfunnel,name='createfunnel'),
    path('createseq/',views.createsequence,name='createsequence'),
    path('scheduleseq/',views.schedulesequences,name='schedulesequences'),
    path('activate/',views.startfunnel,name='startfunnel'),
    path('completed/',views.viewcompleted,name='viewcompleted'),
    path('ongoing/',views.viewongoing,name='viewongoing'),
    path('inactive/',views.viewinactive,name='viewinactive'),
    path('customtem/',views.customtemplate,name='customtemplate'),
    path('viewcustomtem/',views.displaycustomtemplate,name='displaycustomtemplate'),
    path('editcustomtem/<int:customtem_pk>',views.editcustomtemplate,name='editcustomtemplate'),
]

hiringchallenge/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.loginuser,name="loginuser"),
    path('logout/',views.logoutuser,name="logoutuser"),
    path('contacts/',include('contacts.urls')),
    path('funnels/',include('funnels.urls')),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

funnels/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator 
from django.conf import settings


class DefaultTemplates(models.Model):
    template = models.TextField()

    def __str__(self) -> str:
        return self.template

class Funnel(models.Model):
    CHOICES = (
        ('D', 'Draft'),
        ('O', 'Ongoing'),
        ('C', 'Completed'),
    )
    created_by       = models.ForeignKey(
      settings.AUTH_USER_MODEL, 
      on_delete=models.CASCADE,
      null=True,
      blank=True
    )
    funnel_name      = models.CharField(max_length=60)
    segment          = models.CharField(max_length=60,default="General")
    sub_segment      = models.CharField(max_length=60,blank=True)
    no_of_seq        = models.PositiveSmallIntegerField(default=1)
    start_date       = models.DateField(null=True)
    status           = models.CharField(max_length=20,choices=CHOICES,default='D')
    seqs_remaining   = models.PositiveSmallIntegerField(default=1)


    # def __str__(self) -> str:
    #     return self.funnel_name
    

class Sequence(models.Model):
    funnel_id     = models.ForeignKey('Funnel',on_delete=models.CASCADE,null=True)
    sequence_name = models.CharField(max_length=60)
    description   = models.CharField(max_length=60)
    frequency     = models.PositiveSmallIntegerField(default=3,validators=[MinValueValidator(3)])
    sequence      = models.ForeignKey('DefaultTemplates',on_delete=models.CASCADE,null=True)
    sch_date      = models.DateField(null=True)

    def __str__(self) -> str:
        return self.sequence_name

funnels/forms.py
from statistics import mode
from django import forms
from django.db import models
from django.db.models import fields
from .models import Sequence,Funnel,DefaultTemplates

class FunnelForm(forms.ModelForm):
    class Meta:
        model = Funnel
        fields = ['funnel_name','segment','sub_segment']

class SequenceForm(forms.ModelForm):
    # sequence = forms.ModelMultipleChoiceField(queryset=DefaultTemplates.objects.all(),initial=0)
    class Meta:
        model = Sequence
        fields = ['sequence_name','description','frequency','sequence']
    def __init__(self, *args, **kwargs):
        super(SequenceForm, self).__init__(*args, **kwargs)
        self.fields['sequence'].empty_label = "Choose a template"


class DefaultTemplatesForm(forms.ModelForm):
    class Meta:
        model = DefaultTemplates
        fields = '__all__'

funnels/views.py
from pprint import pprint
from typing import Counter
from django import forms
from django.http import request
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render,get_object_or_404
from funnels.forms import SequenceForm,FunnelForm,DefaultTemplatesForm
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.urls import reverse
from django.shortcuts import get_object_or_404,get_list_or_404
from .models import Funnel,Sequence,DefaultTemplates
from contacts.models import ContactInfo
import re
from django.db.models import Q
from django.db import IntegrityError
from datetime import datetime,date,timedelta
# sendgrid related imports
from sendgrid import SendGridAPIClient
import os
from sendgrid.helpers.mail import *
from decouple import config
import time
# messages
from django.contrib import messages
# usermodel
from django.contrib.auth import get_user_model
#----------------------------------------------------
@login_required(login_url='/')
def starterforfunnel(request):    
     return render(request,'starterforfunnel.html')

@login_required(login_url='/')
def createfunnel(request):
     if(request.method=='POST'):
          form1 = FunnelForm(request.POST)
          if(form1.is_valid()):
               curr_form = form1.save()
               request.session['funnelID'] = curr_form.id #We need it later for settingup seqs
               curr_form.created_by = request.user
               curr_form.save()
               # incrementing no of funnels created by user 
               request.user.no_of_funnels+=1
               request.user.save()
               return HttpResponseRedirect(reverse('funnels:createsequence'))
     else:
          form1 = FunnelForm()
          return render(request,'createfunnel.html',{'form1':form1})

@login_required(login_url='/')
def createsequence(request):
     if(request.method=='POST'):
          form2 = SequenceForm(request.POST)
          # getting obj of the funnel created
          funnel_instance = get_object_or_404(Funnel, id=request.session.get('funnelID'))
          if(form2.is_valid()):
               curr_seq = form2.save(commit=False)
               # setting the foreign key
               curr_seq.funnel_id = funnel_instance
               funnel_instance.no_of_seq+=1
               curr_seq.save()
               return HttpResponseRedirect(reverse('funnels:createsequence'))
     else:
          form2 = SequenceForm()
          return render(request,'createsequence.html',{'form2':form2})
 

@login_required(login_url='/')
def schedulesequences(request):
     if(request.method=='POST'):
          string_start_date = request.POST['StartDate']
          start_date = datetime.strptime(string_start_date,'%b %d, %Y').date()
          funnel_instance = get_object_or_404(Funnel, id=request.session.get('funnelID'))
          funnel_instance.start_date = start_date

          # calculating and saving it
          funnel_instance.seqs_remaining=funnel_instance.no_of_seq=Sequence.objects.filter(funnel_id=request.session.get('funnelID')).count()
          funnel_instance.save()

          # Generating dates for sequences associated with the funnel
          seqs = Sequence.objects.filter(funnel_id=request.session.get('funnelID'))
          for seq in seqs:
               seq.sch_date = start_date
               seq.save()
               start_date += timedelta(days=seq.frequency)
          messages.warning(request, 'Sequences Scheduled')
          return HttpResponseRedirect(reverse('funnels:starterforfunnel'))

def sendgrid(to_email,fillin_template,mail_subject,request):
     sg = SendGridAPIClient(api_key='') 
     from_email = Email("tinktankstudio@gmail.com") 
     to_email = To(to_email)    
     subject = mail_subject
     content = Content("text",fillin_template)
     mail = Mail(from_email, to_email, subject, content)
     response = sg.client.mail.send.post(request_body=mail.get())
     print(f'\033[34mstatus code->{response.status_code}.\033[0m')
     # print(response.body,'\n')
     # print(response.headers,'\n')


def updatefunnel(request,seq):
     try:
          curr_funnel = seq.funnel_id
          curr_funnel.seqs_remaining -=1
          curr_funnel.save()
          if(curr_funnel.seqs_remaining==0):
               seq.funnel_id.status = 'C'
          else:
               seq.funnel_id.status = 'O'
          seq.funnel_id.save()
     except IntegrityError:
          messages.add_message(request, messages.INFO, 'No pending funnels for today')
          return 'cancel'


@login_required(login_url='/')
def startfunnel(request):
     today_dateobj = date.today()
     seqs = Sequence.objects.filter(sch_date=today_dateobj)
     counter = 0
     for seq in seqs:
          flag_for_repeated_fun = updatefunnel(request,seq)
          if(flag_for_repeated_fun == 'cancel'):
               continue
          counter+=1
          mail_subject = seq.description
          chosen_template = str(seq.sequence)
          merged_fields = re.findall(r"\{([A-Z a-z _]+)\}", chosen_template)

          # Creating a dict to replace placeholders in template
          d = {}
          for merged_field in merged_fields:
               if(merged_field=='segment' or merged_field=='sub_segment'):
                    d[merged_field] = getattr(seq.funnel_id,merged_field)

          # Filtering records that matches the segment & sub_segment
          matched_records = ContactInfo.objects.filter(Q(segment__icontains=seq.funnel_id.segment)&Q(sub_segment__icontains=seq.funnel_id.sub_segment))

          # Iterating through the matchedrecords and fetching necessary details
          for matching_record in matched_records:
               for merged_field in merged_fields:
                    if(merged_field not in ['segment','sub_segment']):
                         d[merged_field]=getattr(matching_record,merged_field)
               fillin_template = chosen_template.format(**d) # generic template to personal one
               to_email = getattr(matching_record,'email')
               print("\033[34mEntering sendgrid module.\033[0m")
               # pprint(fillin_template)
               sendgrid(to_email,fillin_template,mail_subject,request)
          print('\033[34mUpdating funnels\033[0m')
     if(counter!=0):
          counter_msg = f'Emails are sent! {counter} sequence(s) found for today'
          messages.success(request,counter_msg)
     time.sleep(1)
     return HttpResponseRedirect(reverse('funnels:starterforfunnel'))
     


def viewcompleted(request):
     if(request.method=='GET'):
          com_funnels = Funnel.objects.filter(status='C')
          return render(request,'completedfunnels.html',{'com_funnels':com_funnels})


def viewongoing(request):
     if(request.method=='GET'):
          ongoing_funnels = Funnel.objects.filter(status='O')
          return render(request,'ongoingfunnels.html',{'ongoing_funnels':ongoing_funnels})


def viewinactive(request):
     if(request.method=='GET'):
          inactive_funnels = Funnel.objects.filter(status='D')
          return render(request,'inactivefunnels.html',{'inactive_funnels':inactive_funnels })

@login_required(login_url='/')
def customtemplate(request):
     if(request.method=='GET'):
          return render(request,'createtemplates.html')
     else:
          custom_template = request.POST.get('template_data', False)
          pprint(custom_template)
          obj = DefaultTemplates(template=custom_template)
          obj.save()
          messages.success(request, 'Template saved')
          return HttpResponseRedirect(reverse('funnels:starterforfunnel'))

@login_required(login_url='/')
def displaycustomtemplate(request):
     all_templates_objs = DefaultTemplates.objects.all()
     return render(request,'viewtemplates.html',{'objs':all_templates_objs})


@login_required(login_url='/')
def editcustomtemplate(request,customtem_pk):
     if(request.method=='GET'):
          selected_custom_template_obj = DefaultTemplates.objects.filter(id=customtem_pk).first()
          selected_custom_template_form = DefaultTemplatesForm(instance=selected_custom_template_obj)
          return render(request,'edittemplates.html',{'form':selected_custom_template_form})
     else:
          form = DefaultTemplatesForm(request.POST)
          form.save()
          return HttpResponseRedirect(reverse('funnels:starterforfunnel'))

funnels/templates/base.html
{% load materializecss %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
      $(document).ready(function(){
        $('select').formSelect();
      });
      $(document).ready(function(){
        $('.datepicker').datepicker();
       });
       $(document).ready(function(){
         $('.collapsible').collapsible();
       });
       $(document).ready(function() {
        $('textarea').characterCounter();
       });
       $(document).ready(function() {
        $('.card-alert > button').on('click', function(){
            $(this).closest('div.card-alert').fadeOut('slow');
        })
    })
    </script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Compiled and minified CSS -->
    <meta name = "viewport" content = "width = device-width, initial-scale = 1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel = "stylesheet"
         href = "https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>Hiring lastmile system</title>
</head>
<body>
<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo"><i class="large material-icons" style="margin-left: 8px;">work</i>Welcome {% if user.is_authenticated %} {{ user.username }} {% endif %}👋</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if not user.is_authenticated %}
            <li><a href="{% url 'loginuser' %}">Login</a></li>
            {% endif %}
            {% if user.is_authenticated %}
            <li><a id="dont" href="{% url 'contacts:home' %}">Contacts</a></li>
            <li><a id="dont" href="{% url 'funnels:starterforfunnel' %}">Funnel</a></li>
            <li><a id="dont" href="#">Stats</a></li>
            <li>
                <a href="#" onclick="$('#signOutBtn').click()">Logout</a>
                <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
                     {% csrf_token %}
                     <button id="signOutBtn" type="submit">Logout</button>
                 </form>
            </li>
            {% endif %}
        </ul>
</nav>
<br>
{% block content %}

{% endblock %}

</body>
</html>

funnels/templates/completedfunnels.html
{% extends "base.html" %}
{% load materializecss %}

{% block content %}

<div class="container">
    {% if com_funnels %}
    <ul class="collapsible teal lighten-2">
        {% for com_funnel in com_funnels %}
        <li>
          <div class="collapsible-header"><i class="medium material-icons">cloud_done</i> {{ com_funnel.funnel_name }}
          </div>
          <div class="collapsible-body">
            <span style="margin-right: 20px;">No of sequences: {{com_funnel.no_of_seq}}</span>
            <span style="margin-right: 20px;">Segment: {{com_funnel.segment}}</span>
            <span style="margin-right: 20px;">Subsegment: {{com_funnel.sub_segment}}</span>
            <span style="margin-right: 20px;">Scheduled Date: {{com_funnel.start_date}}</span>
          </div>
        </li>
        {% endfor %}    
    </ul>
    {% else %}
    <h2 style="text-align: center;"><i class="material-icons medium">cloud_off</i> No completed funnels</h2>
    {% endif %}
</div>

{% endblock %}

funnels/templates/createfunnel.html
{% extends "base.html" %}
{% block content %}

<div class="container" style="margin-top:50px ;">
<form action="" method="POST">
    <fieldset><legend>Funnel</legend>
        {% csrf_token %}
        {{ form1 }}
        <br>
        <input class="btn waves-effect" type="submit" value="submit">
    </fieldset>
</form>
<br>
</div>

{% endblock %}

funnels/templates/createsequence.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top:50px ;">
    <form action="" method="POST">
        <fieldset><legend>Sequence</legend>
        {% csrf_token %}
        {{ form2 }}
        <br>
        <input class="btn waves-effect green" type="submit" value="submit">
        </fieldset>
    </form>
    <br>
    <div class="container">
        <form action="{% url 'funnels:schedulesequences' %}" method="POST">
            {% csrf_token %}
            <div class="input-field">
                <label for="StartDate">Starting Date</label>
                <input type="text" class="datepicker" name="StartDate" id="StartDate">
                <input class="btn waves-effect red lighten-1 text-darken-4" type="submit" value="Schedule">
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function() {
    $('a').click(function(event) {
            var answer = window.confirm("Please pick a date to schedule the sequence(s)");
            if(answer){
                event.preventDefault();
                event.stopPropagation();
            }
    });
});
</script>
{% endblock %}

    <!-- <div class="center-align">
        <a class="btn waves-effect teal" href="{% url 'funnels:enoughofsequences' %}">Sequences Done</a>
    </div> -->

funnels/templates/createtemplates.html
{% extends "base.html" %}
{% load materializecss %}
{% block content %}
<script src="https://cdn.tiny.cloud/1/xzphby2gqa7j7lgqubc71ze6da29obhqwhbwimxi1uosqsvh/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
          selector: '#mytextarea',
          menubar: false,
          toolbar: ''
        });
      </script>
<div class="container">
    <h5 style="text-align: center;" >Type your custom template</h5>

    <!-- <form action="" method="POST">
        {% csrf_token %}
        <div class="input-field">
            <i class="material-icons prefix">mode_edit</i>
            <textarea name="template_data" id="text1" class="materialize-textarea"></textarea>
        </div>
        <input class="btn" type="submit" value="Create">
    </form>
    <br> -->
        
    <form action="" method="POST">
        {% csrf_token %}
        <textarea id="mytextarea" name="template_data">Hello, World!</textarea><br>
        <input class="btn" type="submit" value="Create">
    </form><br>

    <div class="input-field" style="width: 50%;margin-left: 18rem;">
        <select name="insert_text" id="insert">
            <option value="{full_name}">Full Name</option>
            <option value="{first_name}">First Name</option>
            <option value="{last_name}">Last Name</option>
            <option value="{designation}">Designation</option>
            <option value="{phone_number}">Phone Number</option>
            <option value="{key_skills}">Key Skills</option>
            <option value="{segment}">Segment</option>
            <option value="{sub_segment}">Sub Segment</option>
        </select>
    </div>

    <button style="margin-left: 18rem;" class="btn green accent-3" onclick="setTextToCurrentPos()">
        Add the mergefield
    </button>

</div>


<script>
function setTextToCurrentPos() {
        let text_to_insert = $("#insert").val();
        tinymce.activeEditor.execCommand('mceInsertContent', false, text_to_insert);
        /*
        var curPos = document.getElementById("mytextarea").selectionStart;
        console.log(curPos);
        let x = $("mytextarea").val();
        let text_to_insert = $("#insert").val();
        $("mytextarea").val(x.slice(0, curPos) + text_to_insert + x.slice(curPos));
        */
        }
</script>
{% endblock %}

funnels/templates/edittemplates.html
{% extends "base.html" %}
{% load materializecss %}

{% block content %}
<script src="https://cdn.tiny.cloud/1/xzphby2gqa7j7lgqubc71ze6da29obhqwhbwimxi1uosqsvh/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#id_template',
        menubar: false,
        toolbar: ''
    });
    </script>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="btn waves-effect" type="submit" value="submit">
    </form>
</div>
<!-- Add mergefields dropbox -->
<div class="input-field" style="width: 50%;margin-left: 18rem;">
    <select name="insert_text" id="insert">
        <option value="{full_name}">Full Name</option>
        <option value="{first_name}">First Name</option>
        <option value="{last_name}">Last Name</option>
        <option value="{designation}">Designation</option>
        <option value="{phone_number}">Phone Number</option>
        <option value="{key_skills}">Key Skills</option>
        <option value="{segment}">Segment</option>
        <option value="{sub_segment}">Sub Segment</option>
    </select>
</div>
<button style="margin-left: 18rem;" class="btn green accent-3" onclick="setTextToCurrentPos()">
    Add the mergefield
</button>


<script>
    function setTextToCurrentPos() {
            let text_to_insert = $("#insert").val();
            tinymce.activeEditor.execCommand('mceInsertContent', false, text_to_insert);
            }
    </script>
{% endblock %}

funnels/templates/inactivefunnels.html
{% extends "base.html" %}
{% load materializecss %}

{% block content %}

<div class="container">
    {% if inactive_funnels %}
    <ul class="collapsible amber accent-3">
        {% for inactive_funnel in inactive_funnels %}
        <li>
          <div class="collapsible-header"><i class="medium material-icons">cloud_done</i> {{ inactive_funnel.funnel_name }}
          </div>
          <div class="collapsible-body">
            <span style="margin-right: 20px;">No of sequences: {{inactive_funnel.no_of_seq}}</span>
            <span style="margin-right: 20px;">Segment: {{inactive_funnel.segment}}</span>
            <span style="margin-right: 20px;">Subsegment: {{inactive_funnel.sub_segment}}</span>
            <span style="margin-right: 20px;">Scheduled Date: {{inactive_funnel.start_date}}</span>
          </div>
        </li>
        {% endfor %}    
    </ul>
    {% else %}
    <h2 style="text-align: center;"><i class="material-icons medium">cloud_off</i> No Inactive funnels</h2>
    {% endif %}
</div>

{% endblock %}

funnels/templates/ongoingfunnels.html
{% extends "base.html" %}
{% load materializecss %}

{% block content %}

<div class="container">
    {% if ongoing_funnels %}
    <ul class="collapsible amber accent-3">
        {% for ongoing_funnel in ongoing_funnels %}
        <li>
          <div class="collapsible-header"><i class="medium material-icons">cloud_done</i> {{ ongoing_funnel.funnel_name }}
          </div>
          <div class="collapsible-body">
            <span style="margin-right: 20px;">No of sequences: {{ongoing_funnel.no_of_seq}}</span>
            <span style="margin-right: 20px;">Segment: {{ongoing_funnel.segment}}</span>
            <span style="margin-right: 20px;">Subsegment: {{ongoing_funnel.sub_segment}}</span>
            <span style="margin-right: 20px;">Scheduled Date: {{ongoing_funnel.start_date}}</span>
          </div>
        </li>
        {% endfor %}    
    </ul>
    {% else %}
    <h2 style="text-align: center;"><i class="material-icons medium">cloud_off</i> No Ongoing funnels</h2>
    {% endif %}
</div>

{% endblock %}

funnels/templates/starterforfunnel.html
{% extends "base.html" %}
{% load materializecss %}

{% block content %}

{% if messages %}
<div class="card-alert card grey" style="width: 90vh;margin-left: 65vh;">
  {% for message in messages %}
  <div class="card-content {{message.tags}}-text">
      <strong>Success! </strong>{{ message }}
  </div>
  <button type="button" class="close {{message.tags}}-text" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
  </button>
  {% endfor %}
</div>
{% endif %}




<div class="container">
  <iframe id="loading" style="display: none;margin-left: 18em;"  src="https://gifer.com/embed/1amw" width=480 height=480.000 frameBorder="0" allowFullScreen></iframe>
  <h4 style="text-align: center;" id="wait"></h4>
  <h3 style="text-align: center;">Funnel<h4></h4>
  <div class="row">
    <div class="col s3"><div class="rectangle"><a class="flow-text" href="{% url 'funnels:createfunnel' %}">Create a new one</a></div></div>
    <div class="col s3"><div class="rectangle"><a class="flow-text" href="{% url 'funnels:viewongoing' %}">View ongoing</a></div></div>
    <div class="col s3"><div class="rectangle"><a class="flow-text" href="{% url 'funnels:viewcompleted' %}">View Completed</a></div></div>
    <div class="col s3"><div class="rectangle"><a class="flow-text" href="{% url 'funnels:viewinactive' %}">View Inactive</a></div></div>
  </div>
  <div class="row">
    <div class="col s4"><div class="rectangle2"><a class="flow-text" href="{% url 'funnels:customtemplate' %}">Create Custom Templates</a></div></div>
    <div class="col s4"><div class="rectangle2"><a class="flow-text" href="{% url 'funnels:displaycustomtemplate' %}">Edit Custom Templates</a></div></div>
    <div class="col s4"><div class="rectangle1"><a id="activate" class="flow-text" href="{% url 'funnels:startfunnel' %}">Activate pending ones</a></div></div>
  </div>
</div>


  
<script>
    $('#activate').click(function(){
      let gif = document.getElementById("loading");
      gif.style.display='block';
      document.getElementById('wait').innerText='Processing...'

    });
</script>

{% endblock %}

funnels/templates/viewtemplates.html
{% extends "base.html" %}
{% load materializecss %}

{% block content %}

<div class="container">
    {% if objs %}
        {% for obj in objs %}
        <div class="card teal lighten-1">
            <div class="card-content white-text">
                <p>{{ obj.template }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'funnels:editcustomtemplate' obj.id %}">
                    Edit the template
                </a>
            </div>
        </div>
        {% endfor %}    
    {% else %}
    <h2 style="text-align: center;"><i class="material-icons medium">cloud_off</i> No templates found</h2>
    {% endif %}
</div>
{% endblock %}