contacts/urls.py
from os import name
from django.urls import path
from . import views
app_name = 'contacts'

urlpatterns=[
    path('',views.home,name='home'),
    path('manual/',views.manualEntry,name='manualEntry'),
    path('match/',views.matchFields,name='matchFields'),
]

funnels/urls.py
from os import name
from django.urls import path
from . import views
app_name = 'funnels'

urlpatterns=[
    path('',views.starterforfunnel,name='starterforfunnel'),
    path('createfun/',views.createfunnel,name='createfunnel'),
    path('createseq/',views.createsequence,name='createsequence'),
    path('scheduleseq/',views.schedulesequences,name='schedulesequences'),
    path('activate/',views.startfunnel,name='startfunnel'),
    path('completed/',views.viewcompleted,name='viewcompleted'),
    path('ongoing/',views.viewongoing,name='viewongoing'),
    path('inactive/',views.viewinactive,name='viewinactive'),
    path('customtem/',views.customtemplate,name='customtemplate'),
    path('viewcustomtem/',views.displaycustomtemplate,name='displaycustomtemplate'),
    path('editcustomtem/<int:customtem_pk>',views.editcustomtemplate,name='editcustomtemplate'),
]

hiringchallenge/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.loginuser,name="loginuser"),
    path('logout/',views.logoutuser,name="logoutuser"),
    path('contacts/',include('contacts.urls')),
    path('funnels/',include('funnels.urls')),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/models.py
from django.db import models
from django.db.models.aggregates import Count
from django_countries.fields import CountryField
from django.core.validators import FileExtensionValidator

class ContactInfo(models.Model):
    CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('T', 'Transgender'),
    )
    full_name   = models.CharField(max_length=100)
    first_name  = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=30,blank=True,default="")
    last_name   = models.CharField(max_length=30,blank=True,default="")
    company     = models.CharField(max_length=30)
    designation = models.CharField(max_length=30,blank=True,default="")
    email       = models.EmailField(primary_key = True,max_length=62)
    aadhar_id   = models.CharField(max_length=15,blank=True,default="")
    pancard_id  = models.CharField(blank=True,max_length=10,default="")
    phone_number= models.CharField(unique=True,max_length=10)
    location    = models.TextField(max_length=500,default="")
    gender      = models.CharField(max_length=20,choices=CHOICES)
    title       = models.CharField(blank=True,max_length=50,default="")
    department  = models.CharField(blank=True,max_length=50,default="")
    university  = models.CharField(max_length=50,default="")
    degree      = models.CharField(max_length=50,default="")
    passing_year= models.CharField(blank=True,max_length=4,default="")
    college     = models.CharField(max_length=50,blank=True,default="")
    linkedin    = models.URLField(verbose_name = "LinkedIn URL",max_length=50,blank=True,default="")
    facebook    = models.URLField(verbose_name = "Facebook URL",max_length=50,blank=True,default="")
    instagram_id= models.CharField(blank=True,verbose_name = "Instagram ID",max_length=50,default="")
    industry    = models.CharField(blank=True,max_length=50,default="")
    country     = CountryField(blank_label='(select country)',blank=True,default='India')
    state       = models.CharField(max_length=35)
    zipcode     = models.CharField(max_length=12)
    key_skills  = models.CharField(max_length=50)
    total_exp   = models.CharField(verbose_name = "Total Experience",default="",max_length=15)
    years_in_business = models.CharField(blank=True,default="",max_length=4)
    cin_no      = models.CharField(blank=True,verbose_name="CIN NO",max_length=30,default="")
    turnover    = models.CharField(blank=True,max_length=30,default="")
    date_of_incorporation =  models.CharField(blank=True,default="",max_length=12)
    employees   = models.CharField(blank=True,default="",max_length=100)
    ctc         = models.CharField(max_length=10)
    notes       = models.TextField(blank=True,default="")
    remarks     = models.TextField(blank=True,default="")
    next_act    = models.CharField(blank=True,max_length=100,default="")
    udf01       = models.CharField(blank=True,max_length=100,default="")
    udf02       = models.CharField(blank=True,max_length=100,default="")
    udf03       = models.CharField(blank=True,max_length=100,default="")
    udf04       = models.CharField(blank=True,max_length=100,default="")
    udf05       = models.CharField(blank=True,max_length=100,default="")
    udf06       = models.CharField(blank=True,max_length=100,default="")
    udf07       = models.CharField(blank=True,max_length=100,default="")
    udf08       = models.CharField(blank=True,max_length=100,default="")
    udf09       = models.CharField(blank=True,max_length=100,default="")
    udf10       = models.CharField(blank=True,max_length=100,default="")
    segment     = models.CharField(max_length=50,default="General",blank=True)
    sub_segment = models.CharField(max_length=50,blank=True)

    def __str__(self):
        return self.full_name


class Upload(models.Model):
    upload_file  = models.FileField(upload_to='.',validators=[FileExtensionValidator( ['csv','xlsx','xls'] ) ])
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{str(self.upload_file)}'

contacts/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import Upload,ContactInfo
from django_countries.widgets import CountrySelectWidget

class ContactInfoForm(forms.ModelForm):
    class Meta:
        model = ContactInfo
        fields = ('full_name','first_name','middle_name','last_name','company','designation','email','aadhar_id','pancard_id','phone_number','location','gender','title','university','country','degree','passing_year','college','linkedin','facebook','instagram_id','industry','state','zipcode','total_exp','years_in_business','cin_no','turnover','date_of_incorporation','employees','ctc','notes','remarks','next_act','segment','sub_segment')
        widgets = {
            'country': CountrySelectWidget(),
            }

          

class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ('upload_file',)

contacts/views.py
from os import name
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.urls.base import reverse
from contacts.models import Upload,ContactInfo
from .forms import UploadForm,ContactInfoForm
from django.http import HttpResponse
import pandas as pd
from pprint import pprint
from django.contrib.auth.decorators import login_required
from pathlib import Path
import ast
import openpyxl
from django.contrib import messages
### Global Variables
df = None
names = None

# ------------------------------------------------------------------------------------ #
def home(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            temp = form.save()
            print(f"\033[34m{temp.upload_file.url}.\033[0m")
            # storing the filename uploaded in this session
            request.session['filepath'] = temp.upload_file.url
            return redirect('contacts:matchFields')
    else:
        form = UploadForm()
        return render(request,'contacts/home.html',{'form':form})


# check and return T/F if there's already a mapping done by the user
def offerAChoice(path_to_file)->bool:
    path = Path(path_to_file)
    return path.is_file()


@login_required(login_url='/')
def matchFields(request):
    if(request.method=='POST'):
        '''
        filepath = request.session.get('filepath')
        if(filepath[-3:]=='csv'):
            print();pprint(f'extension -> {filepath[-3:]}')
            filepath = f'.{filepath}'
            df = pd.read_csv(filepath)
        else:  
            # converting excel to csv and then to pandas dataframe
            print();pprint(f'extension -> {filepath[-4:]}')
            filepath = f'.{filepath}'
            df = pd.read_excel(filepath)
            df.to_csv(filepath,index=False)

        df.drop(df.filter(regex="Unnamed"),axis=1, inplace=True)
        names = list(df.columns)
        '''
        global df;global names
        if request.POST.get('checkBox') == None:  # Give a choice for the user if he doesn't want to use prev key value pair
            matched = { key:request.POST.get(key, False) for key in names }
            # saving the mappings done by the user 
            path_to_file = f'./media/{request.user.username}.txt'
            keyvaluepair_file = open('path_to_file', 'wt+')
            keyvaluepair_file.write(str(matched))
            keyvaluepair_file.close()

        else: # Use the prev key value pair requested by user
            path_to_file = f'./media/{request.user.username}.txt'
            file = open(path_to_file) 
            contents = file.read()
            matched = ast.literal_eval(contents)
        df.rename(columns = matched, inplace = True)
        df.set_index("full_name",drop=True)
        dictionary = df.to_dict(orient='index')
        for index, object in dictionary.items():
            model = ContactInfo()
            for key,value in object.items():
                setattr(model, key, value)
            setattr(model, 'index', index)
            model.save()
        messages.success(request, 'Uploaded to the DB')
        return HttpResponseRedirect(reverse('contacts:home'))

    else:
        # all csv/excel files are stored in media dir and named by username itself
        path_to_file = f'./media/{request.user.username}.txt'
        flag = offerAChoice(path_to_file)
        filepath = request.session.get('filepath')
        filepath = f'.{filepath}'

        # check if its csv or xlsx
        if(filepath[-3:]=='csv'):
            df = pd.read_csv(filepath)
        else:  
            # converting excel to csv and then to pandas dataframe
            df = pd.read_excel(filepath)
            df.to_csv(filepath,index=False)

        df.drop(df.filter(regex="Unnamed"),axis=1, inplace=True) # drop unnamed fields
        names = list(df.columns) # show the cols in the uploaded excel sheet
        pprint(names)
        fields = [field.name for field in ContactInfo._meta.get_fields()] # get contactDB fields
        fields = sorted(fields,key=str.lower)
        # change the file extension
        if(filepath[-4:]=='xlsx'):
            pnt_to_file = Path(filepath)
            pnt_to_file.rename(pnt_to_file.with_suffix('.csv'))

        # pprint(fields)
        return render(request,'contacts/matching.html',{'names':names,'fields':fields,'flag':flag})

@login_required(login_url='/')
def manualEntry(request):
    if(request.method=='GET'):
        form = ContactInfoForm()
        return render(request,'contacts/fillupform.html',{'form':form})
    else:
        form = ContactInfoForm(request.POST)
        if(form.is_valid()):
            form.save()
            return HttpResponse('Homepage')
        else:
            return render(request,'fillupform.html',{'form':form})

contacts/templates/contacts/base.html
{% load materializecss %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS Section -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>Hiring lastmile system</title>
    <!-- JS Section -->
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

    <script>
    $(document).ready(function(){

    // Initialize materialize data picker
    $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
    $('select').formSelect();
    $(document).ready(function() {
        $('.card-alert > button').on('click', function(){
            $(this).closest('div.card-alert').fadeOut('slow');
        })})

    });
    </script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins&display=swap');
    body{
      font-family: 'Poppins', sans-serif;
    }
    </style>
</head>
<body>

<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo"><i class="large material-icons" style="margin-left: 8px;">work</i>Welcome {% if user.is_authenticated %} {{ user.username }} {% endif %}👋</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if not user.is_authenticated %}
            <li><a href="{% url 'loginuser' %}">Login</a></li>
            {% endif %}
            {% if user.is_authenticated %}
            <li><a href="{% url 'contacts:home' %}">Contacts</a></li>
            <li><a href="{% url 'funnels:starterforfunnel' %}">Funnel</a></li>
            <li><a href="#">Stats</a></li>
            <li>
                <a href="#" onclick="$('#signOutBtn').click()">Logout</a>
                <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
                     {% csrf_token %}
                     <button id="signOutBtn" type="submit">Logout</button>
                 </form>
            </li>
            {% endif %}
        </ul>
</nav>
<br>
{% block content %}

{% endblock %}


</body>
</html>

contacts/templates/contacts/fillupform.html
{% extends "contacts/base.html" %}
{% load materializecss %}
{% block content %}

<div class="container">
  <form action="" method="POST">
    {% csrf_token %}
    {{ form|materializecss }}
    <br>
    <input class="btn btn-success" type="submit" value="submit">
  </form>
</div>
<br>
{% endblock %}

contacts/templates/contacts/home.html
{% extends "contacts/base.html" %}
{% load materializecss %}
{% block content %}

<!-- <div class="container" style="margin-top: 80px;">
    <div class="row">
        <div class="col s5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|materializecss }}
                <button style="margin-left:0.7em;" class="btn green" type="submit">Submit
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
        <div class="col s4" style="margin-left: 80px;">
            <label>Enter your contact manually</label><br>
            <a href="{% url 'contacts:manualEntry' %}" class="btn green">Click here<i class="material-icons right">edit</i></a>
        </div>
    </div>
</div> -->
{% if messages %}
{% for message in messages %}
<div class="card-alert card green lighten-2">
    <div class="card-content black-text">
        <strong>success!</strong> {{ message }}
    </div>
    <button type="button" class="close black-text" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
{% endfor %}
{% endif %}

<div class="container" style="margin-top:50px ;">
    <form action="" method="POST" enctype="multipart/form-data">
        <fieldset>
        <legend><h5>UPLOAD CSV/XLSX file 📁</h5></legend>
        {% csrf_token %}
        {{ form|materializecss }}
        <button  class="btn green" type="submit">Submit
            <i class="material-icons right">attach_file</i>
        </button>
        </fieldset>
    </form>
    <br>
    <h5 class="center-align">---- OR ----</h5>
    <div class="input-field">
        <fieldset>
            <legend><h5>Manual Entry of contacts✍️</h5></legend>
            <label>Fill the form</label><br>
            <a href="{% url 'contacts:manualEntry' %}" class="btn green">Click here<i class="material-icons right">edit</i></a>
        </fieldset>
    </div>

</div>
   

{% endblock %}

contacts/templates/contacts/matching.html
{% extends "contacts/base.html" %}
{% load materializecss %}
{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {% if flag %}
            <button class="waves-effect waves-light btn-small brown lighten-1" type="submit" name="checkBox">Skip matching</button>
            <a style="vertical-align: bottom;" onclick="M.toast({html: 'You can skip this step & use the previous mappings'})"> <i class="material-icons">help</i></a>
            <br><br>
        {% endif %} 
        {% for name in names %}                       
        {{name}}:  
        <select class="form-select" name="{{name}}">
        {% for field in fields %}
            <option value={{field}}>{{field}}</option>    
        {% endfor %}
        </select>
        {% endfor %}
        <br>
        <button class="btn green darken-3" type="submit" value="submit">Submit <i class="material-icons right">send</i>
        </button>
    </form>
</div>
<br>
{% endblock %}